version: '3'
services:
    db:
        image: postgres
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_DB: ${PGDATABASE}
    app:
        build: .
        image: store-app:ci
        ports:
            - 13000:3000
        volumes:
            - ./:/usr/src/app
